name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - # Ubuntu 20.04 arm64
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 arm64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build artifact
      run: python3 build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets/muhkuh_tester_cli_station-*.tar.gz
